apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Simon6
  name: round-2-simon6
spec:
  answers:
    - questionId: framework
      singleChoice: React
    - questionId: role
      singleChoice: Backender
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Panic
  questionsDigest: sha256:702ad0209dbf657d34664e0e23f53ffb338894d6641b003d1a3952e8e359635e
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T06:58:14Z"
