apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Display-name
  name: round-1-display-name
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:11Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Maartje
  name: round-1-maartje
spec:
  answers:
    - questionId: kubectl
      singleChoice: Yes, every day
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:28Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Spookers
  name: round-1-spookers
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:29Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: NullReferenceException
  name: round-1-nullreferenceexception
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: Yes, cool!
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:31Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Bobby-Tables
  name: round-1-bobby-tables
spec:
  answers:
    - questionId: kubectl
      singleChoice: Yes, every day
    - questionId: kubecon
      singleChoice: "5.000"
    - questionId: cncf
      singleChoice: Yes, cool!
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:37Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Richard
  name: round-1-richard
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:37Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: OutOfScope
  name: round-1-outofscope
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: "10.000"
    - questionId: cncf
      singleChoice: Yes, cool!
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:38Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Laura
  name: round-1-laura
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:41Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Justin
  name: round-1-justin
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: "10.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:40Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Kijk
  name: round-1-kijk
spec:
  answers:
    - questionId: kubectl
      singleChoice: Yes, every day
    - questionId: kubecon
      singleChoice: "15.000"
    - questionId: cncf
      singleChoice: Yes, cool!
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:41Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: W2
  name: round-1-w2
spec:
  answers:
    - questionId: kubectl
      singleChoice: Yes, every day
    - questionId: kubecon
      singleChoice: "15.000"
    - questionId: cncf
      singleChoice: Yes, cool!
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:46Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: PersonalDetails
  name: round-1-personaldetails
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: "10.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:46Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Meat-proxy
  name: round-1-meat-proxy
spec:
  answers:
    - questionId: kubectl
      singleChoice: Yes, every day
    - questionId: kubecon
      singleChoice: "15.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:49Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Div
  name: round-1-div
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: "15.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:49Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Fronteer
  name: round-1-fronteer
spec:
  answers:
    - questionId: kubectl
      singleChoice: What's kubectl?
    - questionId: kubecon
      singleChoice: "10.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:55Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Je-weet-wel
  name: round-1-je-weet-wel
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: What is KubeCon?
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:57Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-1
    voter.configbutler.ai/submitter: Azz
  name: round-1-azz
spec:
  answers:
    - questionId: kubectl
      singleChoice: Once, it scared me
    - questionId: kubecon
      singleChoice: "1.000"
    - questionId: cncf
      singleChoice: "No"
  questionsDigest: sha256:bec00822a858a24eacbdc0c40d9ff9e3c64309e7c5a83942f1a95085ca35aa19
  roundUID: 898ce86c-ee0e-434f-b7d6-823712c71bcf
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-1
  submittedAt: "2026-10-07T09:07:59Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: OutOfScope
  name: round-2-outofscope
spec:
  answers:
    - questionId: framework
      singleChoice: Vue
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: First write wins, the second one sees a conflict
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:25:03Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Display-name
  name: round-2-display-name
spec:
  answers:
    - questionId: framework
      singleChoice: Vue
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Last write wins
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:25:32Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: NullReferenceException
  name: round-2-nullreferenceexception
spec:
  answers:
    - questionId: framework
      singleChoice: Whatever comes out next week
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Panic
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:26:57Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Richard
  name: round-2-richard
spec:
  answers:
    - questionId: framework
      singleChoice: Angular
    - questionId: role
      singleChoice: Frontender
    - questionId: diy
      singleChoice: Never
    - questionId: conflict
      singleChoice: Merge it somehow
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:08Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Azz
  name: round-2-azz
spec:
  answers:
    - questionId: framework
      singleChoice: Whatever comes out next week
    - questionId: role
      singleChoice: Frontender
    - questionId: diy
      singleChoice: I've stopped counting
    - questionId: conflict
      singleChoice: Panic
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:11Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Bobby-Tables
  name: round-2-bobby-tables
spec:
  answers:
    - questionId: framework
      singleChoice: Whatever comes out next week
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Panic
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:14Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Spookers
  name: round-2-spookers
spec:
  answers:
    - questionId: framework
      singleChoice: Angular
    - questionId: role
      singleChoice: Backender
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Last write wins
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:16Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: PersonalDetails
  name: round-2-personaldetails
spec:
  answers:
    - questionId: framework
      singleChoice: Whatever comes out next week
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Panic
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:18Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Meat-proxy
  name: round-2-meat-proxy
spec:
  answers:
    - questionId: framework
      singleChoice: Whatever comes out next week
    - questionId: role
      singleChoice: Full-stack
    - questionId: diy
      singleChoice: 1–3 times
    - questionId: conflict
      singleChoice: Last write wins
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:20Z"
---
apiVersion: examples.configbutler.ai/v1alpha1
kind: QuizSubmission
metadata:
  labels:
    voter.configbutler.ai/round: round-2
    voter.configbutler.ai/submitter: Fronteer
  name: round-2-fronteer
spec:
  answers:
    - questionId: framework
      singleChoice: Angular
    - questionId: role
      singleChoice: Frontender
    - questionId: diy
      singleChoice: Never
    - questionId: conflict
      singleChoice: Last write wins
  questionsDigest: sha256:3c680edd8ec0bd11de56bb090c29281d3a3f8ea2c39b607d54bc3ac399dea628
  roundUID: e2638080-2875-4b35-af58-6c661d19b6fc
  sessionRef:
    group: examples.configbutler.ai
    kind: QuizSession
    name: round-2
  submittedAt: "2026-10-07T09:27:24Z"
