apiVersion: v1
kind: Secret
metadata:
    annotations:
        configbutler.ai/age-recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
        configbutler.ai/backup-warning: REMOVE_AFTER_BACKUP
    name: gitops-reverser-age
    namespace: voter
data:
    20260915.agekey: ENC[AES256_GCM,data:hy86NBm6ZcLjI1FTIa54012lMee2a2D40dgnzuohHwcgtyc2wSZ7BI5IagvvbZrmVUcwWDP209tWyA46HZzWEEix48H/K/NgcwfImooEjHvI/MgJSD5kIgvPatQySnRhHIHkLw==,iv:r6wlXjUPUNg7fKs6o1QShO8BD4O2xjFjAUJUmsvlJVU=,tag:ZYAx3iWylAVe8SqLlFeb5A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMWdIQjNUOUgyZVlsaU56
            ZmdxVk9ZZEdLUFpvTzBSbDE1SnZUdlpLRVJrCjRvQXdNZ0J5ejIrQXFTT0ZvTnAw
            UzBTSW10SUtxSWF5N1VrWWVQVUVHRVkKLS0tIDVWdVZEYW5UdVFmeUxGUGFVa3Rj
            VDhMT3d6K2N6cUpMcitORklBVWUxRjgKeuch5o+Cb2pjpP+Sndhu/hSIZnnFEE2I
            N+oZqbW0YpUsGmZkla7PfPaXoAGoy09FHvDVIniWRCdZpyzLTlExfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:54:32Z"
    mac: ENC[AES256_GCM,data:c+K2fJ7sRfq7LRxA9Xomrgcg3oAQqt5+mBO0s5NDlt3jhN6rmi4S8rnVq/jfyRA3g3Bx/pygFREIo+HIa0XGRg4YI4kZl6uKoyVG1xzA/BGvn0ToQ2NC8U2Vk4o8BG2EUfuMZ0swsOEvNXdI9gspf/B3rh6aUyweRFqlHyZ8I98=,iv:b31dZytmgulNQ2sp0iobm/z00VQX6u+igeB57Mkokbg=,tag:opSHtdHadj2peT2e6nxtKg==,type:str]
    version: 3.13.3
