apiVersion: v1
kind: Secret
metadata:
    annotations:
        configbutler.ai/age-recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
        configbutler.ai/backup-warning: REMOVE_AFTER_BACKUP
    name: gitops-reverser-age
    namespace: voter
data:
    20260915.agekey: ENC[AES256_GCM,data:SGiawIArWmyOZB92vAasDHoJsIA0sOGa9h8cIu6V6Np6c4WrsdnLbJQEfGPmzPmPP4Sqj6l87Wi+eQB4Hc4WrxfisAWwRXWDxWvx71dq0cqpTQVM3R5cxGxIYnpcB1RXVF64tw==,iv:oGDlp/HiF2wCJ0l9oOdT7PZW+TtQoO8dAAkHmiCLkMM=,tag:Ji0FecTdTeaoGJvWy1RxgQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM1NGbjRkeWZxY3Q4UUtk
            b3p2MlBSSHA1SWE0NVFSeFNpSXFwWnJiWFR3Ci9xNGN5dWd5TjVvNXplaSt5S1hU
            eFpsNldnRUdwZVdCTDRSMi8rUm1NNG8KLS0tIDJtQktNTlNXUTRsM28rakhFdXFk
            dk5ybWQwSjIrQmsrVEFBNFcwaTJkbjgKqd4QwLV15/O3SpD2ybEvg68lDS3v4LoS
            rzCO9G1f7OUfLH9Mdnx3K3ILa2wzlVnLgqxoVx4JiI3U36GmkW5x7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:37:36Z"
    mac: ENC[AES256_GCM,data:L0+Opvx3c0sQZXw7abLlhLmBbMGzZmEllOauZXeRBvM6BM4fvtBYznvof7hB2iYsA1H+uQdZI0OstAONTASjHZoZTqZfAtzzcrw3TgbYriwSSlxeSkmxqw3U3DrRFcJ7kto3C4E9HiqdCnY2dbsbjlaaYtjWzApyIbbd6FiA8iA=,iv:P37/opEIOzBDHytCGoTNSUP4L4U+Qk+SGdESzrOuttU=,tag:AAFrZln4OE/x+ljUdpiI8A==,type:str]
    version: 3.13.3
