apiVersion: v1
kind: Secret
metadata:
    name: k8s-audit-trail-signing
    namespace: voter
data:
    signing.key: ENC[AES256_GCM,data:NFiiPZ65mdJtK0ecLgLk4ih2M5M6cSubsoYuC0vpvXDuZZaQ2Qd7fLMy6pxURN0Lqwtfg8qKbHnP3VTfpqTQjLhOH8bhmedkFXVEHA+ISnBX7HzRpqcUU/9IJWWlqw4Z8Ds7Y9kElK8InIgdAbtrOgGuwn0FbvIz4MeBvGXoiGrTFwPQiCDALx+6IqPqNUQBlF88bz5aNY6WL4eDgFHGDvWSbJVipcTtWanYkNPu66XrtKVR3YR438kdJ2VovyiXAdgM3fbnnum73CQJQUkAo6ekjij6NUhz7DprEs8agWw3cs4P9t5wBzO6BxD2mYHCLD+uZBFLpRo1r2naka21ugdGyc81Y36fsBGEFlWervGtG/ik9EbYYNoz/nJ91C8p+lN3y6NP0dEAskdm/9Tz/u+FHj7jqBx1bs+wHwpynNvEM0tDUItGpkP+UBrlDqEuxtE0xrOdbNAsZxzVsnWmiQ8YBxg1I7FDjvvODBo1KmDVTG5vIveLNeA1XjDJox9UWxUNy2tDg+nsRMZhtYbW4Xtz+hxzkJJq92jq9EEJwtNX8KoLe3+G0Y5xHhRVkmBnCPWXpoEWiG9sRvsjEuQK3piUAa+n59XROcUx8A4ErQhFbjAhUz5f4+xnP+SMd1ddYt+8YbVqbEDXGjVZPd7Zb+ENj6K0WE/HQ3J1geNUwCrflYMdjpQNB+vjRQUsinpiX6HHy4yK3JT4AIoSRwOEMViNsJg=,iv:OMrLXyOI6SBrDnsCrYTYaL0JCUwRai2wEB70S9qpRXE=,tag:5Lo1A8K1OMf9+oJ4izvlpw==,type:str]
    signing.pub: ENC[AES256_GCM,data:JC5yjFj/0ALTiE2aM+Nqf9ivwCOn6cEKlcFSztlgMwwnwv7k3Lnd+CsGuSBWiBOxJm63x67zlXfO3Fej+tytudw89kgxQP3agi7BQMQTnWcZFLil1AEPb02liLnZnN9JQOTJll1HaQlUu2U3G+n0040LuZHIGRHEXlIDtIlQgMA2FJdQlPVl0g==,iv:o8Smh6ZhSy7zxfoO/d4Uuof3KVZ/3RKMaJIOC+4N8cI=,tag:bS9W7KZCBMIRFAs0qoiutg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVUJ2eEh4SnptYnNnbVV4
            bHQ5OFZpWWY0ZVYyUFJoY0JNZEl1QXc0V1JVCmJZTmVEY04vZ243MGNPakNkYnhk
            QlNOU25jTVdtTHE4andyN2lJSmRsM0kKLS0tIDJVVnkzWDVDUXhNUGdhRC9OQUJa
            dnprVytSK3JPWTFobHdwcU1MVXczWUUKRruyxznCzwiJ5wqb2t2MOHadYJi18TCV
            v3zCJ6hX9Gbcpj1+ueofkqi8a7wf+Tq+im+azsnojj4Hy47xK3CKdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:54:32Z"
    mac: ENC[AES256_GCM,data:3Ymhua9aNX/CQUpGFzwiSHn5OZbqU4C35qjKRVEKFbOnqvvjwsspE1ViYj+l01s7a8O6J+KFNquloygyViuxn7Vxh8BUKk8w5JRIHgqCsqB+9yShmdDsE+sL50j5I+9tZqL+pxn9cPaOk3irw6JTgw0FBcWBSsiHmEO25HsgoDI=,iv:sKsxbakuFhTytMMqHocIv8fDE+lXPWqYMXZHrCxg7aE=,tag:r9oimu4TfWf/7TeHYjbqkA==,type:str]
    version: 3.13.3
