apiVersion: v1
kind: Secret
metadata:
    name: k8s-audit-trail-signing
    namespace: voter
data:
    signing.key: ENC[AES256_GCM,data:w17G0TsLrKEszkEqwb3ysakzMUsF12I5RJgvB/2YvDrOZL25n6OqLPc0MsVms1Frr2wfGGfG+h4UGe3/mZBbcQXGYeijdv0ot05gU4/5JzRw/Vnm9beZKnr8zLy2FN9i71Z5GZpxPSuf37+MIvBlEorKiGWNhTbpcLW8KLnDvnUAAOR7y5nn6LB0R/Ivhqa2pLbqizAyN21sejt/G/bD11G41HnJFmptZrgiDCd/mknbmBFiDiKNfBMbx+dAtEs/izF8iisfK0Wn7is7VzS0K1MnPpYDHCYoIrs8iS9jgzxtA2q3CABZFOSSBq0EstONRPyepvpau/SUvQRDxHGDKL8aQ5Pv7iUuj/RLCJSbTvxjB6uftJytzPs4r5bz0GTcwuEYkYIMYqkIx7wE7RYiO26qLZP97iiP82dKAtZuRz6CCKvT4pv9aQj4l6uq4SdMqlWdXzwPhQKA1ySivF9sNmTbTe+RP/uasM7zb7rSAyH4kWTQ//TfUbdw0Wer9EjTvAbREhLUE8yKQCY6E3u/3uRHmLWGyMjuyHsmZNVt8mjHeC8wU6F4JriQdFie5H8pdkAv98eHjwHYh7ewmOUmzUm1IZgB3nmk9NOMu6Jzql/QOlzhCX4eAop1NmG+DlvMoSmPkIj4eAO1W0MBEO+5ReSBKu943dpX1IH9U4r3F3n3JhsVrN9iaXRnwQe0+sr5d9ukwihhHquAFlOAjyj4l7d/Vkw=,iv:QlnAqA00Jsutl4ZdNvPjKdY2AyI7WDcbJleMWj9vYyo=,tag:yCO+wSrsR2lbNZyjf0CHFg==,type:str]
    signing.pub: ENC[AES256_GCM,data:nGfr5GA+wX4MEbXZCWaZOo0nUtcupcmnF45QkmPX2aYhN/jRVymyUMjt1CaVwqnpYOGnnFmaUnSS20KGDb7h8FUaNyDrnDqDi70bet7r1iObFgohT1t0TQthNvckG3n2VQYPmdatBrgH3MkkZUbJxhsyQI0ohGHZN4LH6cKOkRTo8DRsRG/k3w==,iv:+QEA6P/x//RJef0CvNtQjLxsB+UgMJLypPM6ZQAe9yk=,tag:1HE9wM1982l0q2cER2yB4Q==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc0FoU3F2NXFoYnZLdjV3
            NXlIMnVwY1doRXdPK0dTc05wTjVSUjRZREVBCnNleFFreUczdXRtTnJic2tlRjRR
            L3MvR1ZIL0lWNlBXcnVXUkFXRUMwNFEKLS0tIHg3dlV0Y0hMUE1qc1BaS1A0VXhZ
            WGovZmtaTC8rMUd4d3NVdUd2TDFHVzQKFJ50U8BAaTtOSiwW7pCpFM1w249nI/qX
            H/3RA7sSgV1k9Qhgg3V9u9H+C/sGAtbrpy2HIL3sOLVfvAshMUnZ8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:37:36Z"
    mac: ENC[AES256_GCM,data:wlLdxsmB6HuiWkYbCunAEUrsTwn371dsx30dOfpfZXMUc40MKVFLk32lrQWbt10Secb5KfMGNNiKFm2aORVL79p1GDrN/Wihvb+hceCjsIQoyc79BJzBk1QzpunJe5cLhA9MxkovJ4e2JBfWELzXP9hqeVhk74KCTMKVVladXq4=,iv:t4N5men/j0WenLPBRXxASQ0/cDuALscs4QQjYHhufRs=,tag:ZHeR+y0xfMB0H/RVeum9PA==,type:str]
    version: 3.13.3
