apiVersion: v1
kind: Secret
metadata:
    name: krm-foyer-session-keys
    namespace: voter
data:
    session-keys: ENC[AES256_GCM,data:YYuySgSgbX9dztNX0JWpm0/UZEYps+lpGO9CRjmHX05Q8Z5lPQPKL+1yXkLCX0Z0Vr/jr9wzByjfN7qg,iv:6EDyjMXK+T0XzVD5cfGeQw0QNWz8pOWS5O9Gxh7uCac=,tag:kRPYbSc8pWrw+g4SQh4kyA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMM3B4SWRqQWJ6dThnYVNt
            dWF0YVlEN0dzR21mMXhKN3hmMDRrZVRlMEJBCnFhSm9sZzRyNWZmWkFCZ0t1aC91
            cGhUUFN2QVFKYWFyUFdpamRaNGlGMmcKLS0tIExSL2UvQjEwcDN3Z0haUzg5ZDBW
            RnFGSElqQzVUcTZLbnRQUWJpNGgzRlEKLY1k+I6xGHT8o3EpkyzzGoDpQemzLyeE
            E45WqJUqKn/dCteEI/hUOE5wGvRjiQ12lmBrMnOF37h8JcT2x4Po8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T14:36:48Z"
    mac: ENC[AES256_GCM,data:4++TyYGi0Lc+dXjLBeqYm6TKd8bN6B9C3atBsFdvfYVpjAOxHTiF57PXnhunqEjUwX1IsGdfTs1e8LrH8MRfCHbyvFSCk+B5iv0D6kc+isai3MEsHMkhdWxtpP6tTHXSXXy5doyAoDzwQPWCjahVUojlxVqw2rRtfPbdSLu/d6A=,iv:KWZ+sEDsO0a8Li7R9myewGdIPrVuWv3MKsRTEYwcJxU=,tag:UEsT7C0sWjc8dZY1UD67LQ==,type:str]
    version: 3.13.3
