apiVersion: v1
kind: Secret
metadata:
    name: room-pass-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:T7MBiEZnzGqtFj0ewSfwf6+JFc5BTfVxA5FuW24ZECqFGvcEaKOrbXinOGY=,iv:3WF+vkS7JBAtwoPcpdAW1qcCB+8kj89jLFpprScGoi4=,tag:vMuRmxpdBr4Z95jgKjXKUA==,type:str]
    hash-key: ENC[AES256_GCM,data:J0LaQR4vYPMWAukIAbdr29Df7WE5NG1A1oYWx3JGfIGhoakp8q1Y9OKwULY=,iv:SxD5FFRrZl0wW4KiE/DFCjnCI4Z7vzpr8grwKV3/DfM=,tag:iycitd01hyPPpCv1zqtj4w==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWWhkdG9WeHgzOHdjZ0JJ
            RDFzTzl6K3FnUytoQ3ZpWG9wS05zNmQ1ems0ClVUdXNEbGYyT0owRXlaaXhpN0Q5
            cEg1STFMQkRVS0NPTXB1UVltdDZoN0UKLS0tIDNxOFdRb3ZWZ0VLWkh0YkJVTXZM
            WnRON3JxMEZGamhpUUhXRVlaUkczZkEKtgpfxBTVX7oWW9v9NQWTL+8JKeV7mvY5
            c8kCg89QQqfW+DONeHZIawilScOgN61AxgU3viUJmPCzDd5wkQ9GTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:37:36Z"
    mac: ENC[AES256_GCM,data:sEmmNXRjmzfM0WEd2AG8evxITwGMOLKBZG3nBmQPjaVgHxpxW+Uwhhwg0dD6bZCQU3Na+cx7TSeKZYrk3GoaLr87Xs2MkWG3AC4FcGvfbAcfXIdK7LYtHOJ7MPQngdbKIwOgyqWHdbgAsYo9NbREopHc24F56k8j9DPzx/mEZV4=,iv:K2Zr+czmiPV7273KyTRbUoDzboC3hgN/dBFjipxA2Rk=,tag:KZ1f2A27wY7N8gRFle95Dg==,type:str]
    version: 3.13.3
