apiVersion: v1
kind: Secret
metadata:
    name: room-pass-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:etbvFChIeEAsMWZ5sgQ31Ddaq7XKdN00FnAcRbhOpkM1yuGLMdTMp1DseJ8=,iv:6r4BTjNFgRl775gHAHQfI1PNc0dJrrdxTutgUKEtAMg=,tag:z1IHHRFKV5FIvuEamSf+lw==,type:str]
    hash-key: ENC[AES256_GCM,data:3bWE4G1wjnLvp/W7RxsJvkx9ww6rR8hgq9cUuPLEwxjhGD+02GvdZHuQTP8=,iv:+r1XCJODNHCANZ5EOondgXu0VS+HYJP3J7EQI8+YDH8=,tag:Ujk1DhbNhbXlln5ectbFGg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUVUyVUFwbXJsU2drSkVC
            d0JpZk52eFcxN0VZQk4rT3pTbEtVdUJHbzBvCk9MYkZiVTRtb0x4S0c4WmtrV0ln
            TjRsdy83UFl0YWo2cEd6ZnI0eFFXRWsKLS0tIDNOV244QllacGpyN2NTN3EvQjBa
            Z3V3QklhUnpVcmV4Z1VYVm5HZmYyYzgKssVo4pSwS7eA2rntF6f+t9aurqLYBXSu
            xTWnDWLOQGEpDVxaFzWrqFB6GNSPKs2OeluqK5dqk/15FnuXj2ElZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:54:32Z"
    mac: ENC[AES256_GCM,data:nkNKj3ro53n2XHANOj2YjDk9qnbcx4RpiRSlQfdqCkggLmnFFZ/NjG70azWUgSo9J6xzi55dMgMCeNZg+lUus7oo6R3OV+RwF/fUVAOabjTZZEr+VCEQ2UT6p1VKhFYQO8jIh3uOm5gpkREJqh39BCi8qKsRzc5au3xhX9rH5gI=,iv:TRwZ0CzFpffkv+fYY4ZjLsQY5dtg1r59QDOhMSQP2d4=,tag:T4lMpvaEUiZCh801j6Mmgg==,type:str]
    version: 3.13.3
