apiVersion: v1
kind: Secret
metadata:
    name: voter-app-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:HcB8JlXscxzeNNiLG0LBw6S/EWwXxyDJhIMi+5zm9dUigEDCKClvLTJ56L3Z450WuJPY62IW6Caar0G/,iv:6wrqz64u/mLoPn6fY6X5rrbTa923SJIOw24/QsA8ZDY=,tag:j/l8qqxOrSlDmT5nckd0Tw==,type:str]
    hash-key: ENC[AES256_GCM,data:2TtmhC4vHzyKQDK/hxFjtkflcaDM2stPvX24mXRtOk4hj7VxRe0WPlYTbTWwV+OC3jNGQeVTwqRMx9LY,iv:vD/mUEumk9suIn3aP7C1vtGKrk3010Fmi6Dbsuty16E=,tag:+JIlhuD02DxvJ0DSraugXQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aDFOZlYvaWhxZkMyMWJU
            K1ZLUy9zQ1ZTT3dhWTdUYUI5NlZzRVZDWlI0CmpheXBKdWJkVGd6eWhmK0RmQ3Mx
            K3kxanNUSWJ0M25PK0tIOHluZTlTblkKLS0tIHNvWlBBSEZQZlVkc0pYQVNUUUw0
            RkZNa3hMNWx1dzFyUWp6NWtXRyt5eTAK1VJ34cIYoF0k+2QrNzIuwpbbB4GdXzwI
            OM9xdf4GSyJBBNRMQ6pt3ZmJXO4VUspAjAc9a6ssmFxofUdX931IFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:54:32Z"
    mac: ENC[AES256_GCM,data:NHwCJxtDjhrp8pwr16qNwA0LcrBzkGJfV46Jmcv8J6ZJOjkequzBIHUPMTgalgrNn2zoMcaBuZi/Z6FsNlBqxJUbZFXyyDdoW3OgQ0UJG81RdwZJYw055FTRWuZnw7CJm8SpN2tcUvCSHjwqp+p8ct/T9u0YmnBh2+VdBfmfJV4=,iv:inxJfeeqX3iD7ZPxmvjv6/KTbQan0JhXFtolVotzwIc=,tag:MMwdbfa4kWNBIzn85DuaUQ==,type:str]
    version: 3.13.3
