apiVersion: v1
kind: Secret
metadata:
    name: voter-oidc-client
    namespace: voter
data:
    VOTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:vdlE1N+ery8Q6zqNGomjSSVyvX+x6LG82fnmMcPh/boEU4bpHDuf4rV+2AVW/ziq2hvNrMeJ6yDLLR1a,iv:s9PcJoPassT1HQlif5KKSO9TpV3+/QKFMkj9MlDkPEE=,tag:BxoHYZuwNhk35750Qih7WQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByYkhzUzFtVDdNb3gxUzdR
            RXJ5VVRPUXYzVGMvUjl1a0tpajRNTU1iOFVrClVHZzFsMWN2YnkyekNSb2NreXlj
            Y1NDYy9rM3BIM2R5WkVWMy8xUHNCOE0KLS0tIENrZXliUmhwS0FnZitjZlp3Y0F1
            b2grYlZldWpTQnFWb2VYbFlITFBSdTgKUnfSgwry7ANexej38xCad/+YNoXNJvEv
            drx0feQEiibMzimekCfjOVyUOmd7HeiupItuKGRec3Y8Nj4f6/i+iA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:37:36Z"
    mac: ENC[AES256_GCM,data:/rvW3jXh+75Hal2yLLli8QD7j0EZyDOOrx2ZXBcmGo6RXStS1CvdzWpndY3qmuXZx6Mk+MmmcjLyY0O0AiSO8DqiA4TPwMsLcI0sC+AoYEUJl23m/ZwyPpYKOnkc2YW4OoYP6YuEVZ8ryHYbqTEQmg3d8/3ETc4WcD7j20fYHGg=,iv:E9n0x6skHRM18QnivwU18/EUv76Ov74Yc7E+STtNHEM=,tag:YaCp9A58ke4tNtp+TEEuMw==,type:str]
    version: 3.13.3
