apiVersion: v1
kind: Secret
metadata:
    name: voter-oidc-client
    namespace: voter
data:
    VOTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:81GCtJgFaC7qAkfSnf1FOQMeC9Krc2H4HHxgeuUlqtCUzuCJ1AKsI6jlhqfajdmamUohxKz2xdYv8MUA,iv:XPyn+19PPz9eeXQPi0AhgiNbjFcNfThcHcd3MxwD2/Y=,tag:BoTCOZ+wxWnYzC+DxwZ8FA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmaEUyemxEcVg5MWZENWpm
            VHRTQlVWV0ZhVTdXcmlWUC9UeEEvdWhUTTNvCmVPNnphaXdBTHVoZHFkSWliZDJV
            MHVVdkxnY0N1TUNHUUU1UlFpYk9vT1UKLS0tIE9CQXFEdnlHT0l5RXV6bjRYVWNt
            T3piL0ZvcFhkUGw1OFBZTXNzVDJlWUUKzzOgO8tPsSh6PreJAhWw6cgf1YLbAfsX
            kwZBvkd00hbYAiFn3cppKq2tZ/C8FO0N5c8jZpFX5NRVHNcTMZae+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T12:54:32Z"
    mac: ENC[AES256_GCM,data:MdxjCj/zklMKqdwo2HJnjRIuSJqDNWqBj6bxTqMflgtMa6MKmcHOMs1nSaS+iKiVtmj0C4Flp8pKhIU5Od/KAtj2jK6K0Qrg8neUFb6qLMJZQbMMrAUb1APfXlFuP0//0yP6hcP8h4+qsiiW+v74yrmQDwlBaek8IGCd+pSE9oo=,iv:r/RPJH+TTgpCyGyg/soro669esAK6/HPuDwC7CLb69Q=,tag:zV0Nm/FjhwSfk+VeoZx3+w==,type:str]
    version: 3.13.3
