apiVersion: v1
kind: Secret
metadata:
    name: voter-app-cookie
    namespace: voter
data:
    block-key: ENC[AES256_GCM,data:Q67Hr02I/qvfWDqHn+KABkc/VSmQgpLluR618qtGy52Wl7Y7XtUupGjIKeDD/6/65amkTutFoh7ZvP39,iv:Nr3+opuXCpzeamoRJ8CmW4LTPW+KK19wKIJnsr05RGY=,tag:DOhFeMHS5liAl00fc7t8ww==,type:str]
    hash-key: ENC[AES256_GCM,data:DWND2dLnfBwqIXhcKBh2H8bsYO3UaCf98k8NknEljaW5bgRgbHDbNpnxgWREF/PhT7YiSegnP94Ix3vR,iv:ChScg0Zi4p9/WZj4xa9j2g0K+wcw+YP05oTUWTa+BOI=,tag:R1eP98NmY0icddWj/TXzrA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdFlNbDFWRStsQnA1UUZX
            QlRLS2pnaFI0M1JYNUgrZzZWazVDVzE3bmlNCkl4S3I4OG1nMGN5cnBMY1dnZWlz
            dGxoeGlPSXd2SitENC9SZFM5Yzg3RE0KLS0tIHFmSEt2cGxqbm40TWFGbnRjYXhi
            K0JRQ0RrVjhqMDlHUGRkY2gySTROaXcKMSa0wuvhabvZBcaJbj7TK5okTakH64sI
            Sk+7LcbRZkzO6Vf46D2PtHdDdDAS15sfFhCCOcDBW0Xpjb3ZAlgECQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1h5x937hxvfljwgajq0c7ft3hq80dr05m376lnlzekcc752nexczsvkskqa
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T07:37:36Z"
    mac: ENC[AES256_GCM,data:k8cUu3HQHFv1F0zex/SvO4MaGuzJi5qq8/fjKsEK1FISXiUE2JFtvwsvdysiYBXbufyOZTAPEVcBL40s68GXnEmoHMDmcOWxYVnAEDLS94U4qOLgvIRE1RwdhSDUqz/gEigK2CPC2FqPoR3Y59g2e217XvzW0sGsUKxs1oX5SsE=,iv:kf9X8DHJFgrhhGZmfs+sJ3Mov1JUQci3j5Y5Cr+N5Rc=,tag:2NiboiCGfvF+04rBPGBNrA==,type:str]
    version: 3.13.3
