apiVersion: examples.configbutler.ai/v1alpha1
kind: CoffeeConfig
metadata:
  name: demo-coffee
spec:
  bannerText: "Free coffee for all?"
  currency: 'IDR'
  products:
    - description: ""
      enabled: true
      name: Quadruple expresso
      priceCents: 300
      sku: coffee-4
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 200
      sku: coffee-5
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-6
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-7
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-8
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-9
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-10
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-11
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-12
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-13
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-14
    - description: ""
      enabled: true
      name: New Coffee
      priceCents: 300
      sku: coffee-15
  shopName: 'Haagse Coffee Shop'
  vouchers: []
